accounts/urls.py
# coding=utf-8
from django.conf.urls import include, url
from django.contrib import admin
from accounts import views

admin.autodiscover()

urlpatterns = [
    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^register/$', views.register, name='register'),
]

contestms/urls.py
from django.conf.urls import url

from contestms import views

urlpatterns = [
    url(r'^$', views.contests_list, name='contests_list'),
    url(r'^contest_list_(?P<pk>[0-9]+)/$', views.contest_detail_list, name='contest_detail_list'),
    url(r'^contest_rank_(?P<pk>[0-9]+)/$', views.contest_detail_rank, name='contest_detail_rank'),
    url(r'^contest_info_(?P<pk>[0-9]+)/$', views.contest_detail_info, name='contest_detail_info'),
    url(r'^question_(?P<c_id>[0-9]+)/(?P<question_id>[0-9]+)/$', views.question_detail, name='question_detail'),

    url(r'^contest_manager/$', views.contest_manager, name='contest_manager'),
    url(r'^manager_contest_(?P<contest_id>[0-9]+)/$', views.manager_contest_detail_list,
                    name='manager_contest_detail_list'),
    url(r'^manager_contest_update_(?P<contest_id>[0-9]+)/$', views.manager_contest_update,
        name='manager_contest_update'),
    url(r'^manager_contest_rank_(?P<pk>[0-9]+)/$', views.manager_contest_rank,
        name='manager_contest_rank'),

    url(r'^about/$', views.about, name='about'),

]

mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^contestms/', include('contestms.urls', namespace='contestms')),
]

contestms/models.py
from __future__ import unicode_literals
from django.contrib.auth.models import AbstractUser
from django.db import models


class Contest(models.Model):
    name = models.CharField(max_length=200)
    start_time = models.DateTimeField('time started')
    duration = models.DurationField()

    def __unicode__(self):
        return self.name


class User(AbstractUser):
    contests = models.ManyToManyField(Contest, through='Contest_user')
    gender = models.CharField(max_length=20)
    class_name = models.CharField(max_length=20)
    stu_id = models.CharField(max_length=20)
    tel_num = models.CharField(max_length=20)
    qq_num = models.CharField(max_length=20)
    comment = models.TextField(null=True)

    def __unicode__(self):
        return self.username


class Question(models.Model):
    contests = models.ManyToManyField(Contest, through='Contest_question')
    title = models.CharField(max_length=200)
    content = models.TextField()
    hint = models.TextField(null=True)

    def __unicode__(self):
        return self.title


class Example(models.Model):
    question = models.ForeignKey(Question)
    input = models.TextField()
    output = models.TextField()


class SubmitInfo(models.Model):
    contest = models.ForeignKey(Contest)
    user = models.ForeignKey(User)
    question = models.ForeignKey(Question)
    sub_time = models.DateTimeField()
    accepted = models.BooleanField(default=False)

    def __unicode__(self):
        return self.user.username + '-' + self.question.title


class Application(models.Model):
    user = models.ForeignKey(User)
    contest = models.ForeignKey(Contest)
    apply_time = models.DateTimeField(auto_now_add=True)
    handled = models.BooleanField(default=False)
    accepted = models.NullBooleanField(default=False, null=True)

    def __unicode__(self):
        return self.user.username + '-' + self.contest.name

    class Meta:
        unique_together = ('user', 'contest')


class GradeInfo(models.Model):
    contest = models.ForeignKey(Contest)
    user = models.ForeignKey(User)
    question = models.ForeignKey(Question)
    accept = models.BooleanField(default=False)
    accept_sub_time = models.DateTimeField(null=True)
    sub_times = models.PositiveSmallIntegerField(default=0)
    wrong_times = models.PositiveSmallIntegerField(default=0)
    is_fb = models.BooleanField(default=False)

    def __unicode__(self):
        return self.user.username + '-' + self.question.title

    class Meta:
        unique_together = ('contest', 'user', 'question')


class Contest_user(models.Model):
    contest = models.ForeignKey(Contest)
    user = models.ForeignKey(User)
    date_joined = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return self.contest.name + '-' + self.user.username

    class Meta:
        unique_together = ('contest', 'user')


class Contest_question(models.Model):
    contest = models.ForeignKey(Contest)
    question = models.ForeignKey(Question)
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ('contest', 'question')

    def __unicode__(self):
        return self.contest.name + '-' + self.question.title

contestms/views.py
# encoding: utf-8
import sys
from datetime import datetime
import time
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from contestms.models import *

reload(sys)
sys.setdefaultencoding('utf-8')

alpha = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'


def contests_list(request):
    temp_var = get_contests_info(request)
    return render(request, 'contestms/index.html', temp_var)


def get_contests_info(request):
    temp_var = {}
    apply_num = []
    applied = []
    accepted = []
    span = []

    now_time = datetime.now()
    now_second = time.mktime(now_time.timetuple())

    temp_var['now_second'] = now_second

    contest_list = Contest.objects.order_by('start_time')
    for contest in contest_list:
        apply_num.append(Application.objects.filter(contest=contest).count())
        applied.append(
            True if request.user.is_authenticated() and
                    Application.objects.filter(user=request.user, contest=contest).count() != 0 else False

        )

        accepted.append(
            True if request.user.is_authenticated() and
                    Application.objects.filter(user=request.user, contest=contest,
                                               accepted=True).count() != 0 else False
        )

        span.append(time.mktime(contest.start_time.timetuple()) - now_second)

    if request.GET.get('u_id') is not None:

        user = User.objects.filter(pk=request.GET.get('u_id'))[0]
        contest = Contest.objects.filter(pk=request.GET.get('c_id'))[0]
        apls = Application.objects.filter(user=user, contest=contest)

        if apls.count() == 0:
            Application.objects.create(user=user, contest=contest)

    temp_var['contest_list'] = dict(zip(contest_list, zip(apply_num, applied, accepted, span)))
    return temp_var


def getSeconds(t):
    return time.mktime(t.timetuple())


def getTimePercentage(c_id):
    contest = get_object_or_404(Contest, pk=c_id)
    used_time = 100 * (getSeconds(datetime.now()) - getSeconds(contest.start_time)) / contest.duration.seconds
    return used_time


@login_required
def contest_detail_list(request, pk):
    temp_var = {}
    questions = Question.objects.filter(contests=pk)

    questions_info = dict(zip(questions, alpha))
    temp_var['questions_info'] = questions_info
    temp_var['c_id'] = pk

    temp_var['used_time'] = getTimePercentage(pk)
    return render(request, 'contestms/contest_detail.html', temp_var)


@login_required
def contest_detail_rank(request, pk):
    temp_var = {'c_id': pk}

    info_items = GradeInfo.objects.filter(contest=pk)
    contestant_list = []
    names = []
    c = None
    for item in info_items:
        if item.user.username not in names:
            if c is not None:
                c.complete_info()
                contestant_list.append(c)
            names.append(item.user.username)
            c = Contestant(item.user.username)

        q = QuestionToCtt()
        q.accepted = item.accept
        q.wrong_times = item.wrong_times
        q.sub_times = item.sub_times
        q.ac_time = item.accept_sub_time
        q.is_fb = item.is_fb
        q.complete_info()

        c.questions.append(q)
    c.complete_info()
    contestant_list.append(c)

    list_info = sorted(contestant_list, cmp=cmp)
    temp_var['list_info'] = list_info

    q_len = len(list_info[0].questions)
    q_alpha = []
    for i in range(q_len):
        q_alpha.append(alpha[i])
    temp_var['q_alpha'] = q_alpha

    temp_var['used_time'] = getTimePercentage(pk)
    return render(request, 'contestms/contest_detail_rank.html', temp_var)


def cmp(x, y):
    if x.ac_num == y.ac_num:
        return x.penalty - y.penalty
    return y.ac_num - x.ac_num


# Question is short of question to contestant, 以区别模板中的Question
class QuestionToCtt(object):
    def __init__(self):
        self.accepted = False
        self.wrong_times = 0
        self.sub_times = 0
        self.ac_time = None
        self.penalty = 0
        self.is_fb = False
        self.id_in_contest = 0

    def complete_info(self):
        if self.accepted:
            self.penalty = self.ac_time.hour * 60 + self.ac_time.minute + self.wrong_times * 20


class Contestant(object):
    def __init__(self, name):
        self.ac_num = 0
        self.penalty = 0
        self.name = name

        self.questions = []

    def complete_info(self):
        for question in self.questions:
            if question.accepted:
                self.ac_num += 1
                self.penalty += question.penalty


@login_required
def contest_detail_info(request, pk):
    temp_var = {'c_id': pk}
    GradeInfo.objects.order_by()
    temp_var['used_time'] = getTimePercentage(pk)
    return render(request, 'contestms/contest_detail_info.html', temp_var)


@login_required
def question_detail(request, c_id, question_id):
    temp_var = {}

    temp_var['used_time'] = getTimePercentage(c_id)
    temp_var['alpha_id'] = alpha[int(question_id) - 1]
    q = get_object_or_404(Question, pk=question_id)
    temp_var['question'] = q
    temp_var['c_id'] = c_id
    examples = Example.objects.filter(question=question_id)
    temp_var['examples'] = examples
    return render(request, 'contestms/question_detail.html', temp_var)


def contest_manager(request):
    if request.user.is_staff is False:
        return HttpResponseRedirect(reverse('contestms:contests_list'))

    temp_var = get_contests_info(request)
    return render(request, 'contestms/contest_manager.html', temp_var)


def manager_contest_detail_list(request, contest_id):
    if request.user.is_staff is False:
        return HttpResponseRedirect(reverse('contestms:contests_list'))

    if request.method == 'POST':
        handle_list = request.POST.getlist('handle_list')
        contest = get_object_or_404(Contest, pk=contest_id)
        for a_id in handle_list:
            a = get_object_or_404(Application, pk=a_id)
            a.handled = True
            a.accepted = True

            Contest_user.objects.create(contest=contest, user=a.user)
            cqs = Contest_question.objects.filter(contest=contest_id)

            for cq in cqs:
                GradeInfo.objects.create(contest=contest, user=a.user, question=cq.question)
            a.save()

    temp_var = {}
    apls = Application.objects.filter(contest=contest_id, accepted=False)
    temp_var['apls'] = apls
    temp_var['c_id'] = contest_id
    return render(request, 'contestms/manager_contest_detail.html', temp_var)


def manager_contest_update(request, contest_id):
    if request.user.is_staff is False:
        return HttpResponseRedirect(reverse('contestms:contests_list'))

    temp_var = {}
    contestants = []
    cus = Contest_user.objects.filter(contest=contest_id)
    for cu in cus:
        contestants.append(cu.user)
    temp_var['contestants'] = contestants

    questions = []
    cqs = Contest_question.objects.filter(contest=contest_id)
    for cq in cqs:
        questions.append(cq.question)
    temp_var['questions_info'] = zip(questions, alpha)

    temp_var['c_id'] = contest_id

    if request.method == 'POST':
        u_id = request.POST.get('u_id')
        q_id = request.POST.get('q_id')
        accepted = request.POST.get('accepted')

        bool_accepted = False if accepted == 'False' else True
        user = get_object_or_404(User, pk=u_id)
        question = get_object_or_404(Question, pk=q_id)
        contest = get_object_or_404(Contest, pk=contest_id)
        now_t = datetime.now()
        sub_t = datetime(1, 1, 1, 0, 0, 0) + (now_t - contest.start_time)

        s = SubmitInfo.objects.create(user=user, question=question,
                                      contest=contest, accepted=bool_accepted,
                                      sub_time=sub_t)
        temp_var['message'] = user.username + u'在' + \
                              str(s.sub_time) + u' 提交 ' + \
                              temp_var['questions_info'][1][1] + question.title + ': ' + \
                              accepted
        temp_var['accepted'] = bool_accepted

        # item = get_object_or_404(GradeInfo, contest=contest_id, user=user, question=question)
        # item.sub_times += 1
        # if bool_accepted and item.accept is False:
        #     item.accept = True
        #     item.accept_sub_time = s.sub_time
        # if not bool_accepted:
        #     item.wrong_times += 1
        # item.save()

        updateGradeInfo(contest_id, user, question, bool_accepted, s.sub_time)
    return render(request, 'contestms/manager_contest_update.html', temp_var)


questionAccepted = []


def updateGradeInfo(c_id, u_id, q_id, accept, sub_time):
    item = get_object_or_404(GradeInfo, contest=c_id, user=u_id, question=q_id)
    item.sub_times += 1
    if accept and item.accept is False:
        item.accept = True
        item.accept_sub_time = sub_time
        if q_id not in questionAccepted:
            questionAccepted.append(q_id)
            item.is_fb = True
    if not accept:
        item.wrong_times += 1
    item.save()


def manager_contest_rank(request, pk):
    if request.user.is_staff is False:
        return HttpResponseRedirect(reverse('contestms:contests_list'))
    temp_var = {'c_id': pk}
    info_items = GradeInfo.objects.filter(contest=pk)
    contestant_list = []
    names = []
    fb = []
    c = None
    for item in info_items:
        if item.user.username not in names:
            if c is not None:
                c.complete_info()
                contestant_list.append(c)
            names.append(item.user.username)
            c = Contestant(item.user.username)

        q = QuestionToCtt()
        q.accepted = item.accept
        q.wrong_times = item.wrong_times
        q.sub_times = item.sub_times
        q.ac_time = item.accept_sub_time
        q.complete_info()
        c.questions.append(q)
    c.complete_info()

contestms/templates/contestms/base.html
<!DOCTYPE html>
<!-- saved from url=(0048)http://v3.bootcss.com/examples/navbar-fixed-top/ -->
<html lang="zh-CN"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    {% load staticfiles %}
    <script src="{% static 'contestms/libs/bootstrap/js/jquery.min.js' %}"></script>
    {% load bootstrap3 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    {% bootstrap_messages %}
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="{% static 'contestms/images/kaola.png' %}">

    <title>{% block title %}USTH-ACM算法与程序设计基地{% endblock %}</title>

    <!-- Custom styles for this template -->
    <link href="{% static 'contestms/css/navbar-fixed-top.css' %}" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->

    <script src="{% static 'contestms/js/ie-emulation-modes-warning.js'%}"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="//cdn.bootcss.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="//cdn.bootcss.com/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <!-- Fixed navbar -->
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% block homePageUrl %}{% url 'contestms:contests_list' %}{% endblock %}">USTH ACM-ICPC</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li {% block listActive %}class="active"{% endblock %}><a href="{% url 'contestms:contests_list' %}">{% block p2 %}比赛列表{% endblock %}</a></li>
            <li {% block aboutActive %}{% endblock %}><a href="{% url 'contestms:about' %}">关于</a></li>
            <li {% block contactActive %}{% endblock %}><a href="">联系我们</a></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            {% if request.user.is_authenticated %}
              <li><a href="#">{{request.user}}</a></li>
              <li><a href="{% url 'accounts:logout' %}">注销</a></li>
            {% else %}
              <li><a href="{% url 'accounts:login' %}">登录</a></li>
            {% endif %}
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>
    <div class="container">
    {% block content %}
    {% endblock %}
    </div>

    <!-- Placed at the end of the document so the pages load faster -->
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="{% static 'contestms/js/ie10-viewport-bug-workaround.js'%}"></script>

  </body>
</html>

contestms/templates/contestms/contest_detail_base.html
{% extends 'contestms/base.html' %}
{% block p2 %}比赛信息{% endblock %}

{% block content %}
<div class="progress">
  <div class="progress-bar" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: {{ used_time }}%;">
    <span class="sr-only">60% Complete</span>
  </div>
</div>

<ul class="nav nav-tabs">
<li role="presentation" {% block list_active %}{% endblock %}><a href="{% url 'contestms:contest_detail_list' c_id %}">题目列表</a></li>
  <li role="presentation" {% block rank_active %}{% endblock %}><a href="{% url 'contestms:contest_detail_rank' c_id %}">排名</a></li>
  <li role="presentation" {% block info_active %}{% endblock %}><a href="{% url 'contestms:contest_detail_info' c_id %}">提交信息</a></li>
</ul>
{% block contest_content %}{% endblock %}

{% endblock %}

contestms/templates/contestms/contest_detail_info.html
{% extends 'contestms/contest_detail_base.html' %}
{% block info_active %}class="active"{% endblock %}

{% block contest_content %}

{% endblock %}

contestms/templates/contestms/contest_manager.html
{% extends 'contestms/base.html' %}

{% block title %}管理界面{% endblock %}
{% block homePageUrl %}{% url 'contestms:contest_manager' %}{% endblock %}


{% block content%}
    <div class="container">
      <table class="table table-hover">
				<thead>
					<tr class="info">
						<th>比赛编号</th>
						<th>比赛名称</th>
						<th>开始时间</th>
						<th>比赛时长</th>
            <th></th>
					</tr>
				</thead>
				<tbody>
        {% for contest, i in contest_list.items %}

          {% if i.1 %}
					<tr class="success">
          {% else %}
          <tr class="error">
          {% endif %}
						<td>{{ forloop.counter }}</td>
            <td><a href="{% url 'contestms:manager_contest_detail_list' contest.id %}"> {{ contest.name }}</a></td>
						<td>{{ contest.start_time }}</td>
						<td>{{ contest.duration }}</td>

            {% if request.user.is_authenticated %}
            <td> <a href="{% url 'contestms:contests_list' %}?u_id={{request.user.id}}&c_id={{ contest.id }}">
                  <span class="badge badge-important">
                    {% if i.1 %}已{% endif %}报名{{ i.0}}
                  </span>
                 </a>
            </td>
            {% else %}
              <td> <a href="{% url 'accounts:login' %}">
                  <span class="badge badge-important">
                    {% if i.1 %}已{% endif %}报名{{ i.0}}
                  </span>
                 </a>
            </td>
           {% endif %}
					</tr>
        {% endfor %}
				</tbody>
			</table>

{% endblock %}

contestms/templates/contestms/index.html
{% extends 'contestms/base.html' %}
{% block title %}
USTH-ACM算法与程序设计基地
{% endblock %}

{% block content%}

<div id="smModal1" class="modal fade bs-example-modal-sm" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel">
  <div class="modal-dialog modal-sm">
    <div class="modal-content">
      <center><p4>请先报名!</p4></center>
    </div>
  </div>
</div>
<div id="smModal2" class="modal fade bs-example-modal-sm" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel">
  <div class="modal-dialog modal-sm">
    <div class="modal-content">
      <center><p4>比赛报名信息待审核！</p4></center>
    </div>
  </div>
</div>


      <!-- Main component for a primary marketing message or call to action -->


    <div class="container">
      <div class="jumbotron">
        <h1>USTH ACM-ICPC</h1>
        <p>欢迎参加黑龙江科技大学ACM/ICPC算法与程序设计基地比赛.</p>
        <p><a class="btn btn-lg btn-primary" href="{% url 'contestms:about' %}" role="button">了解更多»</a></p>
      </div>
      <table class="table table-hover">
				<thead>
					<tr class="info">
						<th>比赛编号</th>
						<th>比赛名称</th>
						<th>开始时间</th>
						<th>比赛时长</th>
            <th></th>
					</tr>
				</thead>
				<tbody>
        {% for contest, i in contest_list.items %}

          {% if i.1 %}
					<tr class="success">
          {% else %}
          <tr class="error">
          {% endif %}
						<td>{{ forloop.counter }}</td>

            {% if i.1 is False %}
              <td><a data-toggle="modal" href="#smModal1" >{{ contest.name }}</a></td>
            {% endif %}

            {% if i.1 and i.2 is False %}
              <td><a data-toggle="modal" href="#smModal2" >{{ contest.name }}</a></td>
            {% endif %}


            {% if i.1 and i.2 %}

              {% if i.3 <= 0 %}
              <td><a href="#myModal{{ forloop.counter }}" data-toggle="modal" >{{ contest.name }}</a></td>
                  <div class="modal fade" id="myModal{{ forloop.counter }}" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                    <div class="modal-dialog" role="document">
                      <div class="modal-content">
                        <div class="modal-header">
                          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                          <h4 class="modal-title" id="myModalLabel">比赛细则(请仔细阅读)</h4>
                        </div>
                        <div class="modal-body">
                          <ul>
                            <li>比赛时长为五小时, 实时更新排名, 请关注排名榜单.</li>
                            <li>比赛期间不得使用手机,U盘等电子设备,不得交头接耳, 不得无故离开座位.违者视为作弊.</li>
                            <li>选手可携带任何非电子类资料, 包括书籍和打印出来的程序等.</li>
                            <li>每完成一题后可举手示意监考人员提交试题.</li>
                            <li>若发现参赛选手有抄袭等作弊行为, 取消比赛资格.</li>
                            <li>若发现有恶意攻击比赛服务器者, 取消比赛资格.</li>
                            <li>如有任何疑问举手示意监考人员.</li>
                          </ul>

                        </div>
                        <div class="modal-footer">



                          <button type="button" class="btn btn-default" data-dismiss="modal">不接受</button>
                          <button type="button" class="btn btn-primary" data-dismiss="modal"
                                  onclick='javascrtpt:window.location.href="{% url 'contestms:contest_detail_list' contest.id %}"'>接受</button>
                        </div>
                      </div>
                    </div>
                  </div>
                {% else %}
                 <td><a href="#myModal{{ forloop.counter }}" data-toggle="modal" >{{ contest.name }}</a></td>
                  <div class="modal fade" id="myModal{{ forloop.counter }}" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                    <div class="modal-dialog" role="document">
                      <div class="modal-content">
                        <div class="modal-header">
                          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                          <h4 class="modal-title" id="myModalLabel">审核通过</h4>
                        </div>
                        <div class="modal-body">


                          {% load staticfiles %}
                          <script src="{% static 'contestms/js/timer.js' %}"></script>
                          <div id="remainSeconds" style="display:none">{{ i.3 }}</div>
                          距比赛开始还有<div id="remainTime" style="font-size:20px;"></div>

                        </div>
                        <div class="modal-footer">
                          <button type="button" class="btn btn-default" data-dismiss="modal">确定</button>
                        </div>
                      </div>
                    </div>
                  </div>

                {% endif %}
            {% endif %}

            <td>{{ contest.start_time }}</td>
						<td>{{ contest.duration }}</td>
            {% if request.user.is_authenticated %}
            <td> <a href="{% url 'contestms:contests_list' %}?u_id={{request.user.id}}&c_id={{ contest.id }}">
                  <span class="badge badge-important">
                    {% if i.1 %}已{% endif %}报名{{ i.0 }}
                  </span>
                 </a>
            </td>
            {% else %}
              <td> <a href="{% url 'accounts:login' %}">
                  <span class="badge badge-important">
                    {% if i.1 %}已{% endif %}报名{{ i.0}}
                  </span>
                 </a>
            </td>
           {% endif %}
					</tr>
        {% endfor %}
				</tbody>
			</table>
      </div>

{% endblock %}

contestms/templates/contestms/manager_contest_detail.html
{% extends 'contestms/base.html' %}

{% block p2 %}比赛信息{% endblock %}

{% block content %}
<div class="progress">
  <div class="progress-bar" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 60%;">
    <span class="sr-only">60% Complete</span>
  </div>
</div>

<ul class="nav nav-tabs">
  <li role="presentation" class="active"><a href="{% url 'contestms:manager_contest_detail_list' c_id %}">申请列表</a></li>
  <li role="presentation"><a href="{% url 'contestms:manager_contest_update' c_id %}">更新</a></li>
  <li role="presentation"><a href="{% url 'contestms:manager_contest_rank' c_id %}">排名</a></li>
</ul>

<form action="" method="post">
{% csrf_token %}
<table class="table table-hover" style="border:1px solid silver;magin-top:50px;">
  <thead>
  <tr class="success">
    <td></td>
    <td>申请编号</td>
    <td>姓名</td>
    <td>班级</td>
    <td>申请时间</td>
    <td></td>
  </tr>
  </thead>
  {% for a in apls %}
  <tr>
    <td></td>
    <td>{{ forloop.counter }}</td>
    <td>{{ a.id }}</td>
    <td>{{ a.user }}</td>
    <td>{{ a.user.class_name }}</td>
    <td>{{ a.apply_time }}</td>
    <td>
      <input type="checkbox" id="blankCheckbox" name="handle_list" value="{{ a.id }}" >
    </td>
  </tr>
  {% endfor %}
</table>
<button type="submit" class="btn btn-primary btn-lg btn-block">确定</button>
</form>
{% endblock %}